# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Clean
      working-directory: src
      run: dotnet clean

    - name: Restore dependencies
      working-directory: src
      run: dotnet restore

    - name: Setup Nuke Global Tool
      run: dotnet tool install --global Nuke.GlobalTool
      
    - name: Run Nuke build
      working-directory: src
      run: nuke

    - name: Publish NuGet Package to GitHub Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: dotnet nuget push artifacts/*.nupkg --source "https://nuget.pkg.github.com/rflechner/index.json" --api-key $GITHUB_TOKEN --skip-duplicate

    - name: Publish NuGet Package symbols to GitHub Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: dotnet nuget push artifacts/*.snupkg --source "https://nuget.pkg.github.com/rflechner/index.json" --api-key $GITHUB_TOKEN --skip-duplicate
